node {
   def commit_id
   stage('Preparation') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"     //lấy git id và luu laị trong temp file                   
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test') {
     nodejs(nodeJSInstallationName: 'nodejs') {
       sh 'npm install --only=dev' // run install test dêpndence
       sh 'npm test' // run file test/test.js
     }
   }
   stage('docker build/push') {
     docker.withRegistry('https://index.docker.io/v1/', 'dockerhub') {. // connect tới docker hub dùng cedential id la dockerhub
       def app = docker.build("tuedtvt/docker-nodejs-demo:${commit_id}", '.').push() // buil và púsh lên docker hub
     }
   }
}
